GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/68dca055c25f75c484fe515f

###
GET http://localhost:3001/api/persons/68da8efc64e8c0b94d53f64

###
DELETE http://localhost:3001/api/persons/68dbf0727db769ffaa2e0c37

###
PUT http://localhost:3001/api/persons/68dca055c25f75c484fe515f
Content-Type: application/json

{
  "name": "hello2",
  "number": "12311111"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "hello",
  "number": "1231"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Kin"
}