GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/2

###
GET http://localhost:3001/api/persons/6

###
DELETE http://localhost:3001/api/persons/4

###
POST https://phonebook-backend-twilight-violet-453.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Kin",
  "number": "1234"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Kin"
}